name: Generate a build and push to Hostinger static files

on:
  push:
    branches:
      - main # The branch name you are committing the new changes to

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v4

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build # The build command of your project

      - name: copy file via ssh scp key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_KEY }}
          port: ${{ secrets.HOSTINGER_PORT }}
          source: /home/runner/work/hthkia.com/hthkia.com/dist/
          target: domains/hthkia.com/public_html/
          strip_components: 3